#!/bin/bash                                                                                         
echo 'ls -na' >>                                                                       #!/bin/bash                                                                                         
echo 'ls -na'
